apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: pressure-data
      tlsSkipVerify: true
    secureJsonData:
      token: L1IXNeWwJ8V6_cY2B08onCntT84JlrRtlj-GiDkkhpU3av5QiIxPr25ljOAnje1SoXIDlCoear6s4BLu8g8R2A==
